name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Construir imagen
        run: docker compose build

      - name: Levantar contenedores
        run: docker compose up -d

      - name: Eliminar imágenes antiguas
        run: docker image prune -f
